# Generated by Django 5.1.2 on 2024-11-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_book_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
